### PR TITLE
Upgrade to latest Ruby

### PR DESCRIPTION
**Pull request by AxelTheGerman**
Had some trouble installing Ruby 3.0.4 so figured might as well upgrade it.

### CODE REVIEW

**Comment by AxelTheGerman** [comment]
Looks like the test matrix only has 3.1 not 3.2 - maybe worth adding?

**Review by seveibar — DISMISSED** [review]
seems ok to me

**Comment by AxelTheGerman** [comment]
Interesting, CI failed with

```
domain_name-0.6.20231109 requires ruby version >= 2.7.0, which is incompatible
with the current version, 2.6.10
```

Not sure where that comes from, will have another look tomorrow or so.

Appreciate the instant feedback on the PRs :bow: you guys rock

**Comment by AxelTheGerman** [comment]
Found the culprit - it was actually the bot that cut the release with 398565cc4c248db5efcc7a899c5a792dab003de9

It upgrade `domain_name` from 0.5.x to 0.6.x which dropped Ruby 2.6 support - https://github.com/knu/ruby-domain_name/blob/master/CHANGELOG.md

However, as Ruby 2.6 and even 2.7 are officially EOL it probably makes sense to update the CI matrix to drop especially 2.6.

```
Ruby 3.0

status: security maintenance
release date: 2020-12-25
normal maintenance until: 2023-04-01
EOL: 2024-03-31 (expected)
Ruby 2.7

status: eol
release date: 2019-12-25
normal maintenance until: 2022-04-01
EOL: 2023-03-31
Ruby 2.6

status: eol
release date: 2018-12-25
normal maintenance until: 2021-04-01
EOL: 2022-04-12
```
from https://www.ruby-lang.org/en/downloads/branches

Will update the PR but this would need a major version upgrade

**Comment by AxelTheGerman** [comment]
Also just to note this is less blocking than the `http` dependency upgrade that was merged in #71 - more of a housekeeping PR

**Pull request closed without merging**
