### PR TITLE
Adds automatically_manage_new_devices to ConnectWebview creation

### PR DESCRIPTION
**Pull request by AxelTheGerman**
This flag was recently added to the JS SDK.

Not sure if it makes sense to keep adding the parameters here or if we should accept a generic `**params` hash and let the server provide error messages about invalid parameters?

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
Yea great question, we're starting to auto generate sdks soon which might also help

**Comment by AxelTheGerman** [comment]
@rchodava is there anything else needed for this PR? I don't have write access in order to merge.

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
Apologies for the delay @AxelTheGerman , giving you some maintainer access in the future for merges- sorry about that.

**Comment by AxelTheGerman** [comment]
No worries but much appreciated the trust and the openness demonstrated by your team here!

**Pull request merged**
